apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend           # This is the name of the ClusterSecretStore that we have created.
    kind: ClusterSecretStore
  target:
    name: database                # Adı database olan bir tane secret yaratacak.
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: secret/database
        property: password
