server:
  port: 8080


#This will come from kubernetes vault by the help of external secret manager.
#spring:
#  datasource:
#    password:


management:
  endpoints:
    web:
      exposure:
        include: health # means please enable and expose all management endpoint supported by the Spring Boot Actuator.
