name: Spring Boot Project CI/CD Pipeline     # The name of the workflow
on:                                          # Specifies the trigger for this workflow.This example uses the push event, so a workflow run is triggered every time someone pushes a change to the repository or merges a pull request
  push:
    branches:
      - main

jobs:                                       # Groups together all the jobs
  test:                                     # Name of the first job
    name: Unit Test
    runs-on: ubuntu-latest                  # Configures the job to run on the latest version of an Ubuntu Linux runner. This means that the job will execute on a fresh virtual machine hosted by GitHub.
    steps:                                  # Groups together all the steps that run in the test job. Each item nested under this section is a separate action or shell script.
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4         # This step uses the actions/setup-java@v3 action to install the specified version of the JDK.
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'

      - name: Cache local Maven repository  # Cache Maven repository locally so that we do not have to install all of them every time when this workflow runs.
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: |                              # The run keyword tells the job to execute a command on the runner.
          mvn clean
          mvn -B package --file pom.xml

      - name: Run Tests
        run: mvn -B test

  build-java-app:
    name: Build and Deploy Spring Boot App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simpleapp:latest

